name: e2e

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Instalar dependências
        run: npm ci
      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps
      - name: Executar E2E
        env:
          BASE_URL: http://localhost:3001
        run: npm run test:e2e
      - name: Publicar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report


